#!/usr/bin/env ruby

require './lib/client_info_file_service/parser'
require './lib/client_info_file_service/version'
require 'optparse'

options = {}
OptionParser.new do |parser|
  parser.on("-v", "--version", "The version of the app") do |value|
    puts ClientInfoFileService::VERSION
    return
  end
end.parse!

service = ClientInfoFileService::Parser.new(ARGV)

return unless service.valid

service.parse
